Repository hmrc/add-taxes-frontend, pull requests merged in 2018-08, with the labels that each got.

#169 Beacd-213
  app/views/employer/ers/addEmployersPAYE.scala.html
  app/views/employer/ers/registerEmployersPAYE.scala.html
  conf/messages.cy
  conf/messages.en
  test/views/employer/ers/AddEmployersPAYEViewSpec.scala
  test/views/employer/ers/RegisterEmployersPAYEViewSpec.scala
  test/views/employer/ers/UseEmployersPAYEViewSpec.scala
Labels: Testing complete

#161 BEACD-40 | Improve content for add NES to BTA
  app/views/other/importexports/nes/getCHIEFRole.scala.html
  app/views/other/importexports/nes/getEoriAndChiefRole.scala.html
  app/views/other/importexports/nes/registerEORI.scala.html
  conf/messages.cy
  conf/messages.en
  test/views/other/importexports/nes/DoYouHaveCHIEFRoleViewSpec.scala
  test/views/other/importexports/nes/GetCHIEFRoleViewSpec.scala
  test/views/other/importexports/nes/GetEoriAndChiefRoleViewSpec.scala
  test/views/other/importexports/nes/RegisterEORIViewSpec.scala
Labels: Testing complete

#166 BEACD-42 | Improve content for adding SDLT to BTA
  conf/messages.cy
  conf/messages.en
  test/views/other/land/stampduty/PaperFormsViewSpec.scala
  test/views/other/land/stampduty/StampDutyViewSpec.scala
Labels: Testing complete

#177 BEACD-229 | Fix single quotes missing from error messages in Welsh
  conf/messages.cy
Labels: Testing complete

#176 BEACD-223 Improve CT enrolment journey
  app/controllers/corporation/DoYouHaveCorpTaxUTRController.scala
  app/forms/corporation/DoYouHaveCorpTaxUTRFormProvider.scala
  app/identifiers/DoYouHaveCorpTaxUTRId.scala
  app/models/corporation/DoYouHaveCorpTaxUTR.scala
  app/utils/NextPage.scala
  app/utils/nextpage/corporation/DoYouHaveCorpTaxUTRNextPage.scala
  app/views/corporation/doYouHaveCorpTaxUTR.scala.html
  conf/app.routes
  conf/application.conf
  conf/messages.cy
  conf/messages.en
  migrations/applied_migrations/DoYouHaveCorpTaxUTR.sh
  test/controllers/corporation/DoYouHaveCorpTaxUTRControllerSpec.scala
  test/forms/corporation/DoYouHaveCorpTaxUTRFormProviderSpec.scala
  test/utils/nextpage/corporation/DoYouHaveCorpTaxUTRNextPageSpec.scala
  test/views/corporation/DoYouHaveCorpTaxUTRViewSpec.scala
Labels: Good to merge, Testing complete

#181 BEACD-232 | Improve content for 'I don't want to do this right now'
  conf/messages.en
  test/views/OrganisationOnlyViewSpec.scala
  test/views/sa/partnership/SetUpNewAccountViewSpec.scala
  test/views/sa/trust/RegisterTrustViewSpec.scala
  test/views/sa/trust/SetUpNewAccountViewSpec.scala
  test/views/vat/moss/iom/RegisterForVATViewSpec.scala
  test/views/vat/moss/ukbased/AddVATFirstViewSpec.scala
  test/views/vat/moss/ukbased/AddVATMOSSViewSpec.scala
  test/views/vat/moss/ukbased/RegisterForVATViewSpec.scala
Labels: Testing complete

#191 BEACD-246: Enrolment Proxy for SharedWorkspaceIndividual
  app/controllers/enrolment/SharedWorkspaceProxyController.scala
  conf/app.routes
  test/controllers/enrolment/SharedWorkspaceProxyControllerSpec.scala
Labels: Good to merge
