Repository hmrc/add-taxes-frontend, pull requests merged in 2018-09, with the labels that each got.

#196 BEACD 252 | information page for registering by phone for directors
  app/controllers/employer/DirectorsRegisterByPhoneController.scala
  app/views/employer/directorsRegisterByPhone.scala.html
  conf/app.routes
  conf/application.conf
  conf/messages.cy
  conf/messages.en
  test/controllers/employer/DirectorsRegisterByPhoneControllerSpec.scala
  test/views/employer/DirectorsRegisterByPhoneViewSpec.scala
Labels: Good to merge, Testing complete

#197 BEACD 253 | partnerships register by phone page
  app/controllers/employer/PartnershipRegisterByPhoneController.scala
  app/views/employer/partnershipRegisterByPhone.scala.html
  conf/app.routes
  conf/messages.cy
  conf/messages.en
  test/controllers/employer/PartnershipRegisterByPhoneControllerSpec.scala
  test/views/employer/PartnershipRegisterByPhoneViewSpec.scala
Labels: Testing complete

#205 BEACD-262 | Improve SA enrolment journey
  app/controllers/sa/AreYouSelfEmployedController.scala
  app/forms/sa/AreYouSelfEmployedFormProvider.scala
  app/identifiers/AreYouSelfEmployedId.scala
  app/models/sa/AreYouSelfEmployed.scala
  app/utils/NextPage.scala
  app/utils/nextpage/sa/AreYouSelfEmployedNextPage.scala
  app/utils/nextpage/sa/SelectSACategoryNextPage.scala
  app/views/sa/areYouSelfEmployed.scala.html
  conf/app.routes
  conf/application.conf
  conf/messages.cy
  conf/messages.en
  test/controllers/sa/AreYouSelfEmployedControllerSpec.scala
  test/forms/sa/AreYouSelfEmployedFormProviderSpec.scala
  test/utils/nextpage/sa/AreYouSelfEmployedNextPageSpec.scala
  test/utils/nextpage/sa/SelectSACategoryNextPageSpec.scala
  test/views/sa/AreYouSelfEmployedViewSpec.scala
Labels: Review complete
