Repository hmrc/add-taxes-frontend, pull requests merged in 2018-06, with the labels that each got.

#102 fixed bug where merge overwrote routing for vat
  app/utils/nextpage/vat/WhichVATServicesToAddNextPage.scala
  test/utils/nextpage/vat/WhichVATServicesToAddNextPageSpec.scala
Labels: Good to merge, Review complete

#110 BEACD-73 | fixed the condition to check for right enrolment
  app/controllers/other/land/SelectATaxController.scala
  test/controllers/other/land/SelectATaxControllerSpec.scala
Labels: Review complete

#108 BEACD-135 | added proxy for de-enrolment urls
  app/config/Binders.scala
  app/config/FrontendAppConfig.scala
  app/controllers/OtherTaxesController.scala
  app/controllers/deenrolment/DeenrolmentProxyController.scala
  app/utils/Enrolments.scala
  app/utils/nextpage/other/aeoi/HaveYouRegisteredAEOINextPage.scala
  app/utils/nextpage/other/alcohol/atwd/AreYouRegisteredWarehousekeeperNextPage.scala
  app/utils/nextpage/other/charity/DoYouHaveCharityReferenceNextPage.scala
  conf/app.routes
  migrations/applied_migrations/DeenrolmentProxy.sh
  project/MicroService.scala
  test/controllers/deenrolment/DeenrolmentProxyControllerSpec.scala
Labels: Good to merge, Review complete

#112 BEACD-45 : Removed para1 from GBD page
  a.out
  app/views/other/gambling/areYouRegisteredGTS.scala.html
  conf/messages.cy
  conf/messages.en
  test/views/other/gambling/AreYouRegisteredGTSViewSpec.scala
Labels: Testing complete
